Ex3 news list
Fox99N/academyAndroid pull request #3
Opened 2018-10-07 15:51 UTC by Fox99N

Fixed ex2-view

2018-10-14 10:45 UTC, Fox99N commented
Добавила всю 3 домашку.

2018-10-14 19:05 UTC, colriot requested changes

2018-10-14 19:05 UTC, colriot commented on app/build.gradle
>          testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
Давай уберём весь мусор, связанный с тестами, пока тестов реальных у тебя нет

2018-10-14 19:05 UTC, colriot commented on app/build.gradle
>          applicationId "com.fox.academy_lesson1"
Можно уже поменять на nytimes или что-то типа того :)

2018-10-14 19:05 UTC, colriot commented on app/build.gradle
>      implementation fileTree(dir: 'libs', include: ['*.jar'])
Тут тоже либ нет, да и папки нет - давай уберём

2018-10-14 19:05 UTC, colriot commented on app/build.gradle
>      testImplementation 'junit:junit:4.12'
Тестовые зависимости

2018-10-14 19:05 UTC, colriot commented on app/build.gradle
> +    implementation 'com.android.support:cardview-v7:27.1.1'
Общую версию библиотек саппортных можно вынести в переменную, как было в коде с Лекции 3 и в домашке

2018-10-14 19:05 UTC, colriot commented on app/src/main/AndroidManifest.xml
> +    <meta-data
А это зачем?

2018-10-14 19:05 UTC, colriot commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".NewListEx.NewActivity2"></activity>
Пустой тэг можно схлопнуть

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
>      public static Button myCardBtn;
Никогда не делай элементы UI `static` иначе будет утечка памяти, переменные не соберутся сборщиком мусора (GC) вместе с использованной активити, а останутся в статических переменных. Плюс, внутри у них (виджетов) есть ссылка на Context, которым будет активити, т.е она тоже утечёт

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
>      public static final String EXTRA_MESSAGE = "EXTRA_MESS";
Все `static` переменные/константы выноси над всеми не `static` перменными

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
Пустая строка

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +        hint = (TextView) findViewById(R.id.text_hint);
hint легко перепутать с атрибутом `hint` у EditText, можно переименовать? Например, в "description" или типа того

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +        myMessage = (EditText) findViewById(R.id.my_msg);
Не особо понятно, что такое my_msg. Суть элемента не отражена в названии

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +        hint = (TextView) findViewById(R.id.text_hint);
У кнопок у тебя суффикт `btn`, а тут почему-то `text` - это префикс. Придерживайся единого стиля

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MyCardActivity.java
> +            case R.id.img_open_github:
То же самое: префикс vs суффикс

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +package com.fox.academy_lesson1.NewListEx;
Пакеты принято именовать маленькими буквами вообще и точно не с большой, потому что путаница с названиями классов возникает, которые именуют с большой буквы

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +/**
Комменты об авторстве где-то есть, где то нет. Придерживайся единого стиля :)
Тут, имхо, они не нужны. Проект целиком твой и так)

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +public class AdapterNewList extends RecyclerView.Adapter<AdapterNewList.ViewHolder> {
Обычно `Adapter` это суффикс

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +public class AdapterNewList extends RecyclerView.Adapter<AdapterNewList.ViewHolder> {
Ещё News - неисчисляемое. В английском языке нет новости в единственном числе - New (это "новый")

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        this.layoutInflater = (LayoutInflater) context.getSystemService(
Можно писать короче `LayoutInflater.from(context)`

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +    public AdapterNewList(List<NewsItem> news, Context context) {
Обычно, когда в параметрах есть Context, его ставят на первое место.

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +    public class ViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
`public` тут не нужен. Всегда старайся минимально-допустимую видимость задавать сущностям. И не расширять её бездумно, оценивать, правильно ли повышать видимость той или иной сущности именно для твоей конкретной задачи или лучше как-то иначе поступить

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        TextView author;
Можно сделать `private`

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +
Пустая строка

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +    public class ViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
Старайся внутренние классы не мешать с методами объемлющего класса. Лучше убрать его в конец файла

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +            itemView.setOnClickListener(this);
Можно сразу устанавливать листенер лямбдой, как было в примере с лекции и домашке.

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        View view = layoutInflater.inflate(R.layout.new_items_list, parent, false);
Можно не заводить лишнюю переменную, если влезает по длине строки

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        holder.author.setText(newsItem.getAuthor());
Хорошо бы весь код по биндингу локализовать в методе `bind` у `ViewHolder`, тогда все вьюшки станут `private` и логика по работе со внутренностями холдера будет внутри холдера

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        holder.itemView.setOnClickListener(new View.OnClickListener() {
Ставишь листенер при создании холдера, в потом при биндинге его переустанавливаешь. Во-первых, получается листенер при создании холдера бесполезен, во-вторых, переприсваивает листенер при каждом бинде - растратно, когда можно его установить единожды при создании холдера.

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +                openNewsActivity(
Какие странные переносы строк 👀

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +
Пустых строки лишние

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        Bundle bundle = new Bundle();
Бандл не нужен. В интент можно писать напрямую

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +
Много лишних пустых строк. По две нет смысла оставлять тоже

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +    private final String ITEM_MESSAGE = "ITEM_MESSAGE";
Это константа, значит нужно её сделать `static final`. Используется для передачи новости, а не сообщения - не отражает свою суть. Ну и плюс, это ключ extras - стоит отразить это в именовании тоже, например, `EXTRA_NEWS_ITEM`. А также, как и все `static` поля вынести перед обычными полями класса наверх

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        this.news = news;
Ещё я бы порекомендовал везде расставить аннотации @Nonnull и @Nullable, как в примере с домашкой. Потому что это подскажет тулам для анализа кода, когда что-то надо проверять на `null`, а когда нет. И поможет найти им потенциальные баги. Ну и в настоящих проектах на это полагаются часто

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/DataUtils.java
> +    public static final String TAG = "NPE";
Почему NPE?

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +    NewsItem getItem(int id) {
Этот метод где-то используется?

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +public class NewActivity2 extends AppCompatActivity {
Что за 2? Нужны нормально отражающие назначение класса имена.

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +public class NewActivity2 extends AppCompatActivity {
Ещё, кстати, хорошая практика выделить BaseActivity для твоего кода. Туда удобно, например, вставить логи так, чтобы все твои активити сразу это изменение подхватили. Либо другой код, который надо будет сделать для всех активити

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsItem.java
> +    private final int imageUrl;
Url не может быть `int` :)
Далее мы будем переходить на реальные модели из сети. Поэтому макетные данные были даны специально в таком формате, как в домашке в гисте. Плюс, картинки должны грузиться из сети, потому что в реальности они именно оттуда и будут грузиться.

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsListActivity.java
> +        context = getApplicationContext();
Почему? Активити - это уже и так Context

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +            itemView.setOnClickListener(this);
И не наследовать тогда интерфейс

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/DataUtils.java
> +                context.getApplicationContext().getResources().getString(R.string.category_panda),
Зачем всё это тянешь из ресурсов? И зачем весь этот гемор с засовыванием этого туда? Если потом всё все равно придёт из сети и тебе эти ресурсы нужны на одно-два задания)

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +    private TextView authorNews;
Лучше привязать названия переменных к типам вьюх, а не к news, т.к. тут и так всё активити про новости)

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +        Bundle bundle = getIntent().getExtras();
Бандл не нужен, можно напрямую из `intent` доставать

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +    private final String ITEM_MESSAGE = "ITEM_MESSAGE";
Прежние комменты про ключи для extras сюда тоже относятся

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        Intent intent = new Intent(context, NewActivity2.class);
Сделай метод статический для запуска NewActivity2 внутри самого этого активити, и его юзай (как было на первой лекции в примерах). Чтобы не размазывать инфу о необходимых параметрах по всем местам использования. Тогда отсюда уберётся константа совсем

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +        if (bundle != null) {
И тогда этот if удалится

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +        imageNews = (ImageView) findViewById(R.id.image_news_big_image);
Приводить к типу необязательно, сейчас метод сам понимает, куда его присваивают

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +        super.onPostResume();
Никогда не засовывай левые `super` методы так. `onPostResume` вызовется системой в свое время. Его не надо вызывать руками ниоткуда, кроме как из переопределённого метода.

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewActivity2.java
> +    protected void onPause() {
А вообще, зачем тут эти пустые тела методов?)

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsItem.java
> +public class NewsItem implements Serializable{
Форматируй код перед коммитом ;)

2018-10-14 19:05 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsListActivity.java
> +
Почему пустой?

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/drawable/horizontal_divider.xml
> +</shape>
Старайся оставлять пустые строки в конце файлов. Тогда не будет вот таких красных маркеров в конце файла и дифы при изменении последних строчек не будут выглядеть стрёмно (с лишней подсвеченной строкой)

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/drawable/horizontal_divider.xml
> +</shape>
Это единственно место, где лишняя пустая строка нужна =)))

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout-land/activity_item_news_activity.xml
> +                android:src="@drawable/panda"
Почему зашита картинка?

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout-land/activity_main.xml
> +        android:layout_gravity="center"
Форматируй код перед коммитом (и вообще всегда), чтобы атрибуты сортировались

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout-land/activity_main.xml
> +        android:layout_weight="0"
Зачем нулевые веса?

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout-land/activity_main.xml
>          />
Разные закрывающие теги, где-то у тебя на той же строке, что и последний атрибут, где-то на новой - придерживайся единого стиля

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout-land/activity_news_list.xml
> +<GridLayout
Ненене, он тут не нужен. За все гриды у нас теперь отвечает Recycler

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout-land/activity_news_list.xml
> +        android:clipToPadding="true"
Почему true?

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout-land/activity_news_list.xml
> +<GridLayout
И поэтому тебе не нужен отдельный layout для альбомной ориентации - там тем же RecyclerView можно обойтись

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/activity_item_news_activity.xml
> +            android:layout_height="240dp"
В константу

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/activity_item_news_activity.xml
> +            app:expandedTitleMarginEnd="64dp"
В константы

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/activity_my_card_activity.xml
> +                android:id="@+id/photo"
Так же, как в случае с кнопками (`_btn`), хорошо бы отражать, что за вью в id

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/activity_my_card_activity.xml
> +                android:background="@drawable/my_photo_i" />
Что значит `_i`?

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/activity_my_card_activity.xml
> +                <View
Можно вынести в отдельный layout, типа `divider` и просто инклюдить его везде, где надо, вместо копирования

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/activity_my_card_activity.xml
> +                    android:layout_gravity="right"
Тут также, как и с паддингами и маржинами, стоит юзать `end` (или `start`). Если тебе реально не нужно именно ПРАВО всегда, независимо от локали

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/activity_news_list.xml
> +<LinearLayout
Оборачивающий LL не нужен. RV сам может быть корнем, как и любая другая вью

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/activity_news_list.xml
> +        android:clipToPadding="true"
Почему true?

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/layout/layoute_items_content.xml
> +<?xml version="1.0" encoding="utf-8"?>
Опечатка - layoutE

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/values/strings.xml
>      <string name="enter_yore_message">Enter yore message</string>
your

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/values/strings.xml
>      <string name="my_text">My text</string>
Что значит Мой текст?

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/values/strings.xml
> +    <string name="category_panda">Panda World</string>
Если делаешь какие-то макетные данные, то лучше выносить их в отдельный файл с соответствующим названием. Чтобы не смешивать с реальными вещами, которые надо локализовывать.

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/values/dimens.xml
> +    <dimen name="text_small_size">10sp</dimen>
Придерживайся единого стиля именования

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/values/dimens.xml
> +    <dimen name="image_small_size">120dp</dimen>
Также, как и с текстами, рекомендую писать весь общий кусок префиксом `image_size_*`

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/values/dimens.xml
>      <dimen name="text_small_size_ad_info">13sp</dimen>
Название

2018-10-14 19:05 UTC, colriot commented on app/src/main/res/values/dimens.xml
>      <dimen name="btn_small_text">15sp</dimen>
Все названия размеров приведи к единому стилю

2018-10-23 17:58 UTC, Fox99N commented on app/src/main/res/values/dimens.xml
> +    <dimen name="text_small_size">10sp</dimen>
done

2018-10-23 17:58 UTC, Fox99N commented on app/build.gradle
>      testImplementation 'junit:junit:4.12'
done

2018-10-23 17:58 UTC, Fox99N commented on app/build.gradle
>      implementation fileTree(dir: 'libs', include: ['*.jar'])
done

2018-10-23 17:58 UTC, Fox99N commented on app/build.gradle
>          applicationId "com.fox.academy_lesson1"
done

2018-10-23 18:04 UTC, Fox99N commented on app/src/main/res/values/dimens.xml
> +    <dimen name="image_small_size">120dp</dimen>
done

2018-10-23 18:23 UTC, Fox99N commented on app/src/main/res/values/dimens.xml
>      <dimen name="btn_small_text">15sp</dimen>
done

2018-10-23 18:24 UTC, Fox99N commented on app/src/main/res/values/strings.xml
> +    <string name="category_panda">Panda World</string>
не сделано

2018-10-23 18:24 UTC, Fox99N commented on app/build.gradle
> +    implementation 'com.android.support:cardview-v7:27.1.1'
done

2018-10-23 18:24 UTC, Fox99N commented on app/build.gradle
>          testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
done

2018-10-23 18:30 UTC, Fox99N commented on app/src/main/AndroidManifest.xml
> +    <meta-data
Пойдем в интернет

2018-10-23 18:33 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
>      public static final String EXTRA_MESSAGE = "EXTRA_MESS";
Done, бес попутал

2018-10-23 18:37 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +        hint = (TextView) findViewById(R.id.text_hint);
Done

2018-10-23 18:46 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +public class AdapterNewList extends RecyclerView.Adapter<AdapterNewList.ViewHolder> {
Ещё и урок английского)

2018-10-23 18:53 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        this.news = news;
Done но есть вопрос. Как правильнее расставлять эти аннотации? Ведь нужно быть уверенным, что параметр точно не может быть null

2018-10-23 19:02 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        holder.author.setText(newsItem.getAuthor());
Имеется ввиду в oncreate?

2018-10-23 19:04 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        View view = layoutInflater.inflate(R.layout.new_items_list, parent, false);
?не поняла

2018-10-23 19:04 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +
Done

2018-10-23 19:05 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +    public AdapterNewList(List<NewsItem> news, Context context) {
Done

2018-10-23 19:06 UTC, Fox99N commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".NewListEx.NewActivity2"></activity>
Done

2018-10-23 19:06 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
>      public static Button myCardBtn;
Done

2018-10-23 19:07 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +        myMessage = (EditText) findViewById(R.id.my_msg);
Done

2018-10-23 19:13 UTC, Fox99N commented on app/src/main/res/layout/activity_news_list.xml
> +<LinearLayout
Учту на будущее

2018-10-23 19:16 UTC, Fox99N commented on app/src/main/res/layout/activity_my_card_activity.xml
> +                    android:layout_gravity="right"
Dine

2018-10-23 19:16 UTC, Fox99N commented on app/src/main/res/layout/activity_my_card_activity.xml
> +                    android:layout_gravity="right"
Done

2018-10-23 19:18 UTC, Fox99N commented on app/src/main/res/values/strings.xml
>      <string name="my_text">My text</string>
Done

2018-10-23 19:24 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +    public class ViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
Done

2018-10-23 19:24 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +            itemView.setOnClickListener(this);
Done

2018-10-23 19:27 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +                openNewsActivity(
Done

2018-10-23 19:29 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +    NewsItem getItem(int id) {
Добавлять пгом количество считать

2018-10-23 19:33 UTC, Fox99N commented on app/src/main/res/drawable/horizontal_divider.xml
> +</shape>
Done

2018-11-12 20:08 UTC, colriot requested changes
Добавил немного замечаний по новому и старому коду

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/DataUtils.java
> +    public static final String TAG = "NewsPositionElement";
А что обозначает это название?

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsItem.java
>  package com.fox.academy_lesson1.NewListEx;
Имя пакета в Java пишется маленькими буквами, snake_case

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsItemActivity.java
> +    private final String EXTRA_NEWS_ITEM = "ITEM_NEWS";
Если константа, то `static final`

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsItemActivity.java
> +
Не надо много пустых строчек подряд делать

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsListActivity.java
> +        context = getApplicationContext();
Эта переменная вообще не нужна

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsListActivity.java
> +    public void onItemClick(NewsItem newsItem) {
Зачем тут эти пустые реализации методов? Тут же нет функционала никакого

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/AdapterNewList.java
> +        this.news = news;
Верно, но это частично и контракт. Т.е если ты где-то поставила аннотацию `@Nonnull`, то те, кто вызывают метод или конструктор, увидят для себя, что нельзя передавать туда то, что может быть `null`. Плюс среда разработки может автоматом находить такие косяки.
Передать туда `null` специально, конечно, можно, но гораздо проще это сделать случайно, когда нет никаких хинтов вообще.

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsListAdapter.java
> +                   openNewsActivity(news.get(getAdapterPosition()));
Не хорошо внутри ViewHolder завязываться на то, какое действие будет происходить по клику. VH - это просто держатель ссылок на вью, он независим от логики обработки событий. Лучше ему извне передавать листнер и присваивать

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsListAdapter.java
>      public class ViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
А зачем тут интерфейс этот? Ты же вообще его методы не используешь.

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/NewListEx/NewsListAdapter.java
> +    private void openNewsActivity(NewsItem newsSeItem) {
Такие вещи должны быть вне адаптера. В адаптер можно передать листенер для обработки кликов, не внутри писать логику создания интентов и завязываться на открытие конкретной активити обычно не стоит. Так ты только усиливаешь связность элементов/классов. Ну и мы говорили про статические методы запуска активити - не забывай.

2018-11-12 20:08 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/SecondActivity.java
>          Bundle bundle = getIntent().getExtras();
bundle не нужен, можно прямо из интента тащить данные

2018-11-13 19:12 UTC, merged