Ex4 thread
Fox99N/academyAndroid pull request #4
Opened 2018-10-29 18:26 UTC by Fox99N

Добавлено упражнение 4 + правки предыдущего 3 и 2 урока. Загрузку картинок с сервера делать не стала,  в полной мере реализую это в 5 упражении.

2018-11-12 20:50 UTC, colriot requested changes
Есть над чем поработать, но многое с прошлой домашки исправила 👍

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +    public Button myCardBtn;
Зачем `public`?

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
>      public void openNewActivivity() {
Зачем он сделан `public`?

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +    public void openThreadActivity() {
Зачем он сделан `public`?

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsItemsActivity.java
> +                Bundle bundle = getIntent().getExtras();
Поехали отступы
`bundle` не нужен - юзай `intent`

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsItemsActivity.java
> +    @Override
Такие пустые методы не нужны, они ничего не делают

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsItemsActivity.java
> +        NewsItem newsItem =(NewsItem) bundle.getSerializable(EXTRA_NEWS_ITEM);
Не забывай форматировать код

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsListActivity.java
> +    protected void onStart() {
Опять

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsListActivity.java
>      protected void onStop() {
Метод пустой - удалить

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsListActivity.java
> +    private Handler h;
Вроде бы нигде не используется

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsListActivity.java
> +            adapterNewList = new NewsListAdapter(newsItems, getApplicationContext());
Использую в качестве контекста активити - `NewsListActivity.this`

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsListActivity.java
> +        protected List<NewsItem> doInBackground(List<NewsItem>... lists) {
Зачем ты тут параметр-список задаёшь? Ты его не юзаешь. Пусть будет `Void`

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/thread_training/ThreadActivity.java
> +        class RightLeg implements Runnable {
Отступы поехали.

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/thread_training/ThreadActivity.java
> +                        object.notify();
Почему решила через `wait` и `notify` делать?

2018-11-12 20:50 UTC, colriot commented on app/src/main/java/com/fox/academy_lesson1/thread_training/ThreadActivity.java
> +
Много лишних пустых строчек)

2018-11-12 20:50 UTC, colriot commented on app/src/main/res/layout-land/activity_main.xml
> +        android:layout_weight="0" />
Зачем веса?

2018-11-12 20:50 UTC, colriot commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_weight="0"
Зачем веса? И не забывай форматировать код

2018-11-12 20:50 UTC, colriot commented on app/src/main/res/layout/activity_thread.xml
> +
Пустой тэг можно схлопнуть

2018-11-12 20:50 UTC, colriot commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_fab">16dp</dimen>
Сгруппируй похожие значения в пачки, расставь пустые строчки между группами, чтобы чуть легче читать было

2018-11-12 20:50 UTC, colriot commented on app/src/main/res/values/dimens.xml
>  </resources>
Про пустые строки в конце файла не забывай

2018-11-12 20:50 UTC, colriot commented on app/src/main/res/values/strings.xml
Не больше одной пустой

2018-11-13 19:51 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +    public Button myCardBtn;
fixed

2018-11-13 19:51 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
> +    public void openThreadActivity() {
fixed

2018-11-13 19:53 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/MainActivity.java
>      public void openNewActivivity() {
fixed

2018-11-13 19:53 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsItemsActivity.java
> +                Bundle bundle = getIntent().getExtras();
fixed

2018-11-13 19:55 UTC, Fox99N commented on app/src/main/java/com/fox/academy_lesson1/new_list_ex/NewsItemsActivity.java
> +    @Override
это про какие? не поняла

2018-11-13 19:59 UTC, Fox99N commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_weight="0"
fixed

2018-11-13 20:04 UTC, Fox99N commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_fab">16dp</dimen>
fixed

2018-11-13 20:04 UTC, Fox99N commented on app/src/main/res/values/dimens.xml
>  </resources>
fixed

2018-11-13 20:05 UTC, Fox99N commented on app/src/main/res/values/strings.xml
fixed

2018-11-15 19:14 UTC, merged